### ISSUE TITLE
Fix broken link in search results

### ISSUE THREAD

**Issue by jhughes982** [raquel-ucl/oracc-search-front-end#59]
If you go to:
[https://build-oracc.museum.upenn.edu/neo/sux?xis=sux.r00755c](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbuild-oracc.museum.upenn.edu%2Fneo%2Fsux%3Fxis%3Dsux.r00755c&data=05%7C02%7Cjames.hughes%40ucl.ac.uk%7Cfc40b714f355407cbd8008dc2d6b659e%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638435186480727713%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=EcnPeDVrYs%2FFVEyCC1evNBoR%2FbCfHbNqGKQuTmSevoY%3D&reserved=0)
and click on the "Ḫattusa (mod. Boğazkale) [2]" link, it doesn't go anywhere. If you do the equivalent on our Oracc search front end it goes into an infinite spin.
Do you know where this link is supposed to go?

Of course I can disable our link easily. Making it do something clever could be tricky in the time we have left (I'm off next week and back the week after).

**Comment by jhughes982** [comment]
The grey links in the Metadata column are supposed to take you to additional information. In the original website the information appears in a popup, which is why the Angular site probably cannot retrieve the data. Steve said he can give us access to the data by embedding an ID in the link. We will wait to hear back from Steve once he has looked into this.

![Screenshot 2024-02-20 at 12 48 47](https://github.com/oracc/oracc-search-front-end/assets/70143648/7b7630bd-bea3-4614-9a84-44824e22dc22)

**Comment by tim-band** [comment]
This is obsolete now with p4pager
